(function(fb,parentModule){var Module={};Module.arguments=[];Module.print=parentModule.print;Module.printErr=parentModule.printErr;Module.cleanups=[];var gb=0;var STACKTOP=getMemory(TOTAL_STACK);assert(STACKTOP%8==0);var STACK_MAX=STACKTOP+TOTAL_STACK;Module.cleanups.push((function(){parentModule["_free"](STACKTOP);parentModule["_free"](gb)}));gb=alignMemory(getMemory(96,4||1));__ATINIT__.push();allocate([119,101,98,0,45,0,45,45,101,109,98,101,100,0,45,45,105,110,116,101,114,97,99,116,105,118,101,0,45,45,110,111,45,105,110,116,101,114,97,99,116,105,118,101,0,101,120,116,101,110,115,105,111,110,115,47,101,109,98,101,100,46,104,0,101,109,98,101,100,95,110,101,119,0,105,115,95,115,109,97,108,108,40,114,41,0],"i8",ALLOC_NONE,gb);function _OL_allocate(){return parentModule["_OL_allocate"].apply(null,arguments)}function _OL_continue(){return parentModule["_OL_continue"].apply(null,arguments)}function _OL_deref(){return parentModule["_OL_deref"].apply(null,arguments)}function _OL_new(){return parentModule["_OL_new"].apply(null,arguments)}function _OL_run(){return parentModule["_OL_run"].apply(null,arguments)}function _OL_userdata(){return parentModule["_OL_userdata"].apply(null,arguments)}function ___assert_fail(){return parentModule["___assert_fail"].apply(null,arguments)}function _strlen(){return parentModule["_strlen"].apply(null,arguments)}function _binary_repl_start(){return parentModule["_binary_repl_start"].apply(null,arguments)}var ASSERTIONS=false;var g$_binary_repl_start=(function(){return parentModule["_binary_repl_start"]});Module.asmGlobalArg={"Math":Math,"Int8Array":Int8Array,"Int16Array":Int16Array,"Int32Array":Int32Array,"Uint8Array":Uint8Array,"Uint16Array":Uint16Array,"Uint32Array":Uint32Array,"Float32Array":Float32Array,"Float64Array":Float64Array,"NaN":NaN,"Infinity":Infinity};Module.asmLibraryArg={"abort":abort,"assert":assert,"enlargeMemory":enlargeMemory,"getTotalMemory":getTotalMemory,"abortOnCannotGrowMemory":abortOnCannotGrowMemory,"setTempRet0":setTempRet0,"getTempRet0":getTempRet0,"_OL_allocate":_OL_allocate,"_OL_continue":_OL_continue,"_OL_deref":_OL_deref,"_OL_new":_OL_new,"_OL_run":_OL_run,"_OL_userdata":_OL_userdata,"___assert_fail":___assert_fail,"_binary_repl_start":_binary_repl_start,"_strlen":_strlen,"g$_binary_repl_start":g$_binary_repl_start,"DYNAMICTOP_PTR":DYNAMICTOP_PTR,"tempDoublePtr":tempDoublePtr,"ABORT":ABORT,"STACKTOP":STACKTOP,"STACK_MAX":STACK_MAX,"gb":gb,"fb":fb};// EMSCRIPTEN_START_ASM
var asm=(/** @suppress {uselessCode} */ function(global,env,buffer) {
"use asm";var a=new global.Int8Array(buffer);var b=new global.Int16Array(buffer);var c=new global.Int32Array(buffer);var d=new global.Uint8Array(buffer);var e=new global.Uint16Array(buffer);var f=new global.Uint32Array(buffer);var g=new global.Float32Array(buffer);var h=new global.Float64Array(buffer);var i=env.DYNAMICTOP_PTR|0;var j=env.tempDoublePtr|0;var k=env.ABORT|0;var l=env.STACKTOP|0;var m=env.STACK_MAX|0;var n=env.gb|0;var o=env.fb|0;var p=0;var q=0;var r=0;var s=0;var t=global.NaN,u=global.Infinity;var v=0,w=0,x=0,y=0,z=0.0;var A=0;var B=global.Math.floor;var C=global.Math.abs;var D=global.Math.sqrt;var E=global.Math.pow;var F=global.Math.cos;var G=global.Math.sin;var H=global.Math.tan;var I=global.Math.acos;var J=global.Math.asin;var K=global.Math.atan;var L=global.Math.atan2;var M=global.Math.exp;var N=global.Math.log;var O=global.Math.ceil;var P=global.Math.imul;var Q=global.Math.min;var R=global.Math.max;var S=global.Math.clz32;var T=env.abort;var U=env.assert;var V=env.enlargeMemory;var W=env.getTotalMemory;var X=env.abortOnCannotGrowMemory;var Y=env.setTempRet0;var Z=env.getTempRet0;var _=env._OL_allocate;var $=env._OL_continue;var aa=env._OL_deref;var ba=env._OL_new;var ca=env._OL_run;var da=env._OL_userdata;var ea=env.___assert_fail;var fa=env._binary_repl_start;var ga=env._strlen;var ha=env.g$_binary_repl_start;var ia=0.0;
// EMSCRIPTEN_START_FUNCS
function ja(a){a=a|0;var b=0;b=l;l=l+a|0;l=l+15&-16;return b|0}function ka(){return l|0}function la(a){a=a|0;l=a}function ma(a,b){a=a|0;b=b|0;l=a;m=b}function na(a,b){a=a|0;b=b|0;if(!p){p=a;q=b}}function oa(a,b,d){a=a|0;b=b|0;d=d|0;var e=0,f=0;e=l;l=l+16|0;f=e;b=ba(b|0)|0;c[a>>2]=b;da(b|0,a|0)|0;c[f>>2]=n+0;c[f+4>>2]=n+4;c[f+8>>2]=n+6;c[f+12>>2]=d|0?n+14|0:n+28|0;b=ca(c[a>>2]|0,4,f|0)|0;if(b&2|0?(b>>>2&31|32|0)==32:0){c[a+4>>2]=b;l=e;return}ea(n+74|0,n+45|0,235,n+64|0)}function pa(a,b){a=a|0;b=b|0;var d=0,e=0,f=0,g=0,h=0;g=l;l=l+16|0;f=g;c[f>>2]=b;d=1;while(1){h=(c[f>>2]|0)+(4-1)&~(4-1);e=c[h>>2]|0;c[f>>2]=h+4;if(!e)break;else d=d+1|0}c[f>>2]=b;e=l;l=l+((1*(d<<2)|0)+15&-16)|0;c[e>>2]=aa(c[a>>2]|0,c[a+4>>2]|0)|0;b=0;do{d=(c[f>>2]|0)+(4-1)&~(4-1);h=c[d>>2]|0;c[f>>2]=d+4;b=b+1|0;c[e+(b<<2)>>2]=h}while((h|0)!=0);h=$(c[a>>2]|0,b|0,e|0)|0;l=g;return h|0}function qa(a){a=a|0;var b=0,d=0;b=l;l=l+16|0;d=b;c[d>>2]=ra(a)|0;c[d+4>>2]=0;pa(n+88|0,d)|0;l=b;return}function ra(a){a=a|0;return ta(a,ga(a|0)|0)|0}function sa(){var a=0;a=ha()|0;oa(n+88|0,a,1);return}function ta(b,d){b=b|0;d=d|0;var e=0,f=0,g=0;g=d+3|0;e=g>>>2;f=_(c[n+88>>2]|0,e|0)|0;c[f>>2]=(g&16777212)-d<<8|(e<<16)+65536|2062;if(d|0){e=f+4|0;while(1){d=d+-1|0;a[e>>0]=a[b>>0]|0;if(!d)break;else{b=b+1|0;e=e+1|0}}}return f|0}function ua(){}

// EMSCRIPTEN_END_FUNCS
return{_embed_eval:pa,_embed_new:oa,_ol_eval:qa,_ol_init:sa,establishStackSpace:ma,runPostSets:ua,setThrew:na,stackAlloc:ja,stackRestore:la,stackSave:ka}})


// EMSCRIPTEN_END_ASM
(Module.asmGlobalArg,Module.asmLibraryArg,buffer);var _embed_eval=Module["_embed_eval"]=asm["_embed_eval"];var _embed_new=Module["_embed_new"]=asm["_embed_new"];var _ol_eval=Module["_ol_eval"]=asm["_ol_eval"];var _ol_init=Module["_ol_init"]=asm["_ol_init"];var runPostSets=Module["runPostSets"]=asm["runPostSets"];var setThrew=Module["setThrew"]=asm["setThrew"];var NAMED_GLOBALS={"ol":88};for(var named in NAMED_GLOBALS){Module["_"+named]=gb+NAMED_GLOBALS[named]}Module["NAMED_GLOBALS"]=NAMED_GLOBALS;parentModule["registerFunctions"]([],Module);__ATPRERUN__.push(runPostSets);if(runtimeInitialized){callRuntimeCallbacks(__ATPRERUN__);callRuntimeCallbacks(__ATINIT__)}return Module})




