(define (get-int16 byte-vector offset)
   (+ (refb byte-vector offset)
      (* (refb byte-vector (+ offset 1)) 256)))

;
;(define (BindTexture texture)
;   (glBindTexture GL_TEXTURE_2D (get texture 'id 0)))

(define (quad x y)
   (glVertex2f x y)
   (glVertex2f x (+ y 1))
   (glVertex2f (+ x 1) (+ y 1))
   (glVertex2f (+ x 1) y))
;(define (quadT x y)
;   (glTexCoord2f 0 0)
;   (glVertex2f x y)
;   (glTexCoord2f 0 1)
;   (glVertex2f x (+ y 1))
;   (glTexCoord2f 1 1)
;   (glVertex2f (+ x 1) (+ y 1))
;   (glTexCoord2f 1 0)
;   (glVertex2f (+ x 1) y))
