name: 'Setup Project Environment'
description: 'checkout submodules, cleanup, build headers'

runs:
  using: "composite"
  steps:
    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Apt update
      run: 'sudo rm -f /var/lib/man-db/auto-update; sudo apt update'

    - name: Make ol/vm.h
      run: 'make includes/ol/vm.h'
