all: train-images-idx3-ubyte.gz \
     train-labels-idx1-ubyte.gz \
      t10k-images-idx3-ubyte.gz \
      t10k-labels-idx1-ubyte.gz

train-images-idx3-ubyte.gz:
	wget -c "https://github.com/fgnt/mnist/raw/refs/heads/master/train-images-idx3-ubyte.gz"
train-labels-idx1-ubyte.gz:
	wget -c "https://github.com/fgnt/mnist/raw/refs/heads/master/train-labels-idx1-ubyte.gz"
t10k-images-idx3-ubyte.gz:
	wget -c "https://github.com/fgnt/mnist/raw/refs/heads/master/t10k-images-idx3-ubyte.gz"
t10k-labels-idx1-ubyte.gz:
	wget -c "https://github.com/fgnt/mnist/raw/refs/heads/master/t10k-labels-idx1-ubyte.gz"
