#!/usr/bin/env -S bash -c "make -s -C ../.. rosettacode-tests"

# tests without test results in %.%.ok file are legal,
#   but can not be used in batch testing!
TEST_FILES += $(patsubst %.ok,%,\
                 $(wildcard tests/rosettacode/*.scm)\
                 $(wildcard tests/rosettacode/*.bin))

.PHONY: rosettacode-tests
.PHONY: rosettacode-tests-native

rosettacode-tests-native:
	DEV_MODE=0 make rosettacode-tests

# enable as part of regression testing
regression-tests: rosettacode-tests

# ------ rosettacode tests ----------------------------------------------
.SILENT: rosettacode-tests
rosettacode-tests: olvm-binaries
rosettacode-tests: RUNNER=ROSETTACODE
rosettacode-tests: $(wildcard tests/rosettacode/*.scm) \
                   $(wildcard tests/rosettacode/sorting_algorithms/*.scm)
	echo " "
	echo "# ROSETTRACODE.ORG OL EXAMPLES"
	FAILMARK=$(shell mktemp -u tmp/fail.rosettacode.XXXXXXXXX) \
	BACKEND_URL=$(BACKEND_URL) RUNNER=$(RUNNER) SESSION=$(SESSION) \
	TESTS="$^" EXECUTABLE=olvm $(MAKE) tests
