#!/bin/bash
./make

export PATH=$PATH:/opt/android/sdk/platform-tools

adb uninstall name.yuriy_chumak.ol

adb shell rm -rf /sdcard/ol/*
adb push main.lisp /sdcard/ol/

adb push ../../libraries/lib /sdcard/ol/lib
adb push ../../libraries/OpenGL /sdcard/ol/OpenGL
adb push ../../libraries/otus /sdcard/ol/otus

adb push splash.png /sdcard/ol

adb install wnd-debug.apk
adb shell pm grant name.yuriy_chumak.ol android.permission.READ_EXTERNAL_STORAGE
adb shell monkey -p name.yuriy_chumak.ol -c android.intent.category.LAUNCHER 1
