#!/bin/bash

cp ../../libraries/lib/gl/config.scm assets/lib/gl/config.scm
cp ../../libraries/lib/gl.scm assets/lib/gl.scm
cp ../../libraries/otus/lisp.scm assets/otus/lisp.scm
cp ../../libraries/otus/random!.scm assets/otus/random!.scm
cp ../../libraries/otus/ffi.scm assets/otus/ffi.scm
cp ../../libraries/OpenGL/ES/version-1-1.scm assets/OpenGL/ES/version-1-1.scm
cp ../../libraries/OpenGL/ES/platform.scm assets/OpenGL/ES/platform.scm

adb shell ps | grep name.yuriy_chumak.ol | awk '{print $2}' | xargs adb shell kill
adb push assets /sdcard
adb shell monkey -p name.yuriy_chumak.ol -c android.intent.category.LAUNCHER 1
