(import (scheme read))
(let loop ((sym (read)))
   (unless (eof? sym)
      (define chars (c/_/ (symbol->string sym)))
      (if (eq? (length chars) 2)
      then
         (display "(#x")
         (display (lref chars 1))
         (display " #T)")
      else
         (define a (string->number (lref chars 1) 16))
         (define b (string->number (lref chars 2) 16))
         (for-each (lambda (x)
               (display "(#x")
               (display (number->string x 16))
               (display " #T)"))
            (iota (- b a -1) a)))
      (print)
      (loop (read))))
