#!/bin/sh

PATH=$PATH:/opt/emsdk_portable:/opt/emsdk_portable/clang/fastcomp/build_master_64/bin:/opt/emsdk_portable/node/4.1.1_64bit/bin:/opt/emsdk_portable/emscripten/master

#gcc -std=c99 -g3 -Wall -fmessage-length=0 -Wno-strict-aliasing -DNAKED_VM oljs.c -o "js" -O2 -g2 -m64
../vm ../repl compile.lisp >program.c
#./js program.b <../tests/numbers.scm
emcc program.c oljs.c -D__EMSCRIPTEN__ -o olvm.html -s ASYNCIFY=1 -O1 -g
#emcc program.c oljs.c -D__EMSCRIPTEN__ -o vm.html -s ASYNCIFY=1 -O2 -s ASSERTIONS=1
#unexpand --first-only -t=2
