(display "#ifndef NAKED_VM\n")
(display "unsigned char *language = (unsigned char*) \"")
;(let for ((n 0) (all (file->list "repl")))
;   (let ((x (car all)))
;      (if (= (mod n 16) 0)
;         (display "\"\n\""))
;      (display "\\x")
;      (display (string (ref "0123456789abcdef" (div x 16))))
;      (display (string (ref "0123456789abcdef" (mod x 16)))))
;   (if (not (null? (cdr all))) (for (+ n 1) (cdr all))))

(for-each (lambda (x)
             (display "\\x")
             (display (string (ref "0123456789abcdef" (div x 16))))
             (display (string (ref "0123456789abcdef" (mod x 16)))))
          (file->list "repl"))
(display "\";")
(display "\n#endif")
(halt 0)