name: build aarch64

on:
  push:
    branches:
      - master

jobs:
  linux-build:
    strategy:
      matrix:
        os: [ ubuntu-24.04-arm ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update submodules
      run: 'git submodule update --init --recursive'

    - name: Build
      run: 'make; make describe'

    - name: Regression tests
      run: 'make describe check'
