name: linux ppc64

on:
  push:
    branches:
      - master

# save resources, stop outdated workflows
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make-check:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update submodules
      run: 'git submodule update --init --recursive'

    - name: Build
      run: 'make; make describe'

    - name: Apt update
      run: 'sudo apt update'

    - name: Install ppc64 toolchain
      run: 'sudo apt install gcc-powerpc64-linux-gnu -y'

    - name: Install qemu ppc (32- and 64-bit both)
      run: 'sudo apt install qemu-system-ppc'

    - name: Start Virtual Framebuffer for X11 tests
      run: 'sudo apt install xvfb; Xvfb :0 -screen 0 1024x768x16 &'

    - name: Regression tests
      run: 'make describe; DEV_MACHINE=1 HAVE_32CDEFS=0 HAVE_64CDEFS=0 HAVE_PPC64=1 DISPLAY=:0.0 make check'
