name: macos intel/m1

on:
  push:
    branches:
      - master

jobs:
  macos-build:
    strategy:
      matrix:
        os: [ macos-13, macos-latest ] # intel, m1
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update submodules
      run: 'git submodule update --init --recursive'

    - name: Build
      run: 'make; make describe'

    - name: Regression tests
      run: 'make describe check'
